### ISSUE TITLE
javascript in your java source

### ISSUE THREAD

**Issue by AtomicStryker** [paigen11/read-file-java#1]
https://github.com/paigen11/read-file-java/blob/fd60d17c66dc2981ee9dc830307230ec1d3ff8be/src/main/java/com/example/readFile/readFileJava/ReadFileJavaApplicationLineIterator.java#L73

"undefined" is a javascript keyword. It would be "null" in java, except in this case, the variable is already guaranteed to not be null (because of earlier code). Your IDE added some static import to "fix" this, but it really should not be there.

**Comment by paigen11** [comment]
Thanks, I've removed the undefined references entirely. I appreciate the note - avoiding null pointer exceptions is something I take seriously (even to the point of overkill). Like I said, Java's not my strongest language, I'm more of a JavaScript girl. 😬
